### ISSUE TITLE
:VroomRunTestFile does nothing (and doesn't give any error either) when using minitest

### ISSUE THREAD

**Issue by PaBLoX-CL** [skalnik/vim-vroom#58]
I have vim-vroom installed, but after calling `:VroomRunTestFile`, nothing happens :/, i don't even get an error. I have tried changing `g:vroom_test_unit_command` to:

+ `'bin/rake test '`
+ `'rake test '`
+ `'bundle exec ake test '`
+ `'bin/rake test TEST='`
+ `'rake test TEST='`

But none of them throws an error. Any idea how can I continue troubleshoot this?

**Comment by styx** [comment]
@PaBLoX-CL, this happens if your tests can't be found. Test files names should end with `_spec.rb` or `_test.rb`. Check it please.
