### ISSUE TITLE
--servername option

### ISSUE THREAD

**Issue by lowski** [skalnik/vim-vroom#68]
Hey,
Thanks for the add-on, I really like it.

I have small questions, I started to move slowly to NeoVim and I encounter strange warning when I run tests with vim-vroom and vim dispatch inside tmux session. I'm receiving this:

`Unknown option argument: "--servername"`

However everything seems to be working fine as tests are executed properly. Is this flag needed for this plugin?

**Comment by styx** [comment]
Hi, I made a search on a repo and there is no such a word `servername` at all. Seems one of the parts of your toolset passes this option to another one and you see the warning. Might be it is related to how processes are started by nvim or might be you have an alias like `nvim --servername`? Of course I might be missing something (:

**Comment by lowski** [comment]
Thanks @styx for your response.

Looks like this option must come from some other plugins that I use, sorry for bringing this issue here. I will close this ticket then.
