### ISSUE TITLE
Odd characters in vim window when using vroom for rspec

### ISSUE THREAD

**Issue by floydj** [skalnik/vim-vroom#71]
Here's an example of what I see in the command window after a spec runs using vroom:

```
[32m  I see a message when choosing a low pro hopper[0m

Finished in 9.52 seconds (files took 0.36624 seconds to load)
[32m1 example, 0 failures[0m 
```

I've looked through the docs, but don't see anything that applies here. How can I get vroom to preserve the same characters I'd see if I ran the spec in my terminal? I'm on Mac OS. I've tried two different fonts w/ Vim just to be sure, but see the same results.

**Comment by skalnik** [comment]
Hmm, I think that's the coloring characters. Perhaps try setting `g:vroom_use_colors` to `0`?

**Comment by floydj** [comment]
Thank you! That fixed the character issue. But of course, I don't have colors now.... Any ideas on how to get that going?

**Comment by skalnik** [comment]
> But of course, I don't have colors now.... Any ideas on how to get that going?

Sadly, I'm not really sure about this one 😕
